"""`stapel-gen-client` — tier-2 project-owned typed client override
(docs/pending/profile-fields.md "Дополнение владельца" §17.07) and its
pre-commit drift/no-op gates.

Generation-invoking tests need a real `node`/`npx` (the generation core is
openapi-typescript, reused via `npx`, per this module's own docstring — not
reimplemented) — they degrade to a skip when neither is on PATH, the same
best-effort posture `_generate_presenters_md` already uses elsewhere in this
repo for a similarly environment-dependent step.
"""
import json
import shutil
from pathlib import Path

import pytest

from stapel_tools.gen_client import GENERATED_OVERRIDE_DIR, main, override_active, run

FIXTURE = Path(__file__).parent / "fixtures" / "docgen"
NODE_AVAILABLE = shutil.which("npx") is not None
requires_node = pytest.mark.skipif(not NODE_AVAILABLE, reason="node/npx not on PATH")


def _plant(tmp_path: Path) -> Path:
    proj = tmp_path / "widgetco"
    docs_dir = proj / "docs"
    shutil.copytree(FIXTURE, docs_dir)
    shutil.move(str(docs_dir / "translations"), str(proj / "translations"))
    return proj


def _add_swap(proj: Path, *, empty: bool = False) -> None:
    settings = proj / "config_settings.py"
    body = "STAPEL_SWAP = {}\n" if empty else (
        'STAPEL_SWAP = {\n    "USERS_PROFILE_PRESENTER": "widgetco.presenters.MyPresenter",\n}\n'
    )
    settings.write_text(body)


class TestOverrideActive:
    def test_false_with_nothing(self, tmp_path):
        proj = tmp_path / "plain"
        proj.mkdir()
        assert override_active(proj) is False

    def test_false_with_empty_stapel_swap(self, tmp_path):
        proj = tmp_path / "plain"
        proj.mkdir()
        _add_swap(proj, empty=True)
        assert override_active(proj) is False

    def test_true_with_nonempty_stapel_swap(self, tmp_path):
        proj = tmp_path / "plain"
        proj.mkdir()
        _add_swap(proj)
        assert override_active(proj) is True

    def test_true_with_manifest_flag(self, tmp_path):
        proj = tmp_path / "plain"
        proj.mkdir()
        (proj / "stapel.override.json").write_text(json.dumps({"clientOverride": True}))
        assert override_active(proj) is True

    def test_false_with_manifest_flag_falsy(self, tmp_path):
        proj = tmp_path / "plain"
        proj.mkdir()
        (proj / "stapel.override.json").write_text(json.dumps({"clientOverride": False}))
        assert override_active(proj) is False

    def test_ignores_swap_mentions_inside_skip_dirs(self, tmp_path):
        proj = tmp_path / "plain"
        proj.mkdir()
        venv_file = proj / ".venv" / "site-packages" / "fake.py"
        venv_file.parent.mkdir(parents=True)
        venv_file.write_text('STAPEL_SWAP = {"X": "y.Z"}\n')
        assert override_active(proj) is False


class TestNoOpGate:
    def test_no_override_is_a_no_op_even_with_a_schema(self, tmp_path):
        proj = _plant(tmp_path)
        assert run(proj) == 0
        out_dir = proj / GENERATED_OVERRIDE_DIR
        assert not out_dir.exists()

    def test_check_is_also_a_no_op_without_override(self, tmp_path):
        proj = _plant(tmp_path)
        assert run(proj, check=True) == 0


@requires_node
class TestGenerationWithOverride:
    def test_generates_schema_ts_when_swap_declared(self, tmp_path):
        proj = _plant(tmp_path)
        _add_swap(proj)
        assert run(proj) == 0
        out = proj / GENERATED_OVERRIDE_DIR / "widgetco" / "schema.ts"
        assert out.is_file()
        text = out.read_text()
        assert "AUTO-GENERATED by `stapel-gen-client`" in text
        assert "openapi-typescript" in text
        assert "Widget" in text  # the fixture schema's component name

    def test_force_generates_without_any_override_signal(self, tmp_path):
        proj = _plant(tmp_path)
        assert run(proj, force=True) == 0
        out = proj / GENERATED_OVERRIDE_DIR / "widgetco" / "schema.ts"
        assert out.is_file()

    def test_check_drift_gate_round_trip(self, tmp_path):
        proj = _plant(tmp_path)
        _add_swap(proj)
        run(proj)
        assert run(proj, check=True) == 0

        out = proj / GENERATED_OVERRIDE_DIR / "widgetco" / "schema.ts"
        out.write_text(out.read_text() + "\n// hand edit\n")
        assert run(proj, check=True) == 1

        assert run(proj) == 0  # regenerate fixes it
        assert run(proj, check=True) == 0

    def test_main_cli_entrypoint(self, tmp_path):
        proj = _plant(tmp_path)
        _add_swap(proj)
        assert main([str(proj)]) == 0
        assert main([str(proj), "--check"]) == 0
