"""§57 owner directive item 7 (as revised) — local env generated by the
framework so a project works right after `clone → docker compose up`, zero
manual config: `.env.local` is COMMITTED (deterministic, recognizably
dev-marked values — never secrets), local-only mock OTP providers, and the
standalone/studio channel-origin presets. Naming canon: `local` = this
machine; `dev`/`stage`/`prod` names (env files AND compose files) are
reserved for STANDS."""
import subprocess
import sys

import pytest
import yaml

from stapel_tools.create_project import create_project


def _create(tmp_path, name="app", modules=None, env_preset="standalone"):
    create_project(
        name=name, project_type="monolith", title=name.capitalize(),
        url="https://x.dev", company_name="X", company_email="x@x.dev",
        modules=modules or ["core"], output_dir=tmp_path,
        use_submodules=False, init_git=False, env_preset=env_preset,
    )
    return tmp_path / name


class TestEnvDevGenerated:
    def test_env_local_is_deterministic_dev_markers_not_secrets(self, tmp_path):
        """Committed canon: every value is a deterministic, recognizable dev
        marker. The SECRET_KEY prefix rides stapel-core prodguard's existing
        `django-insecure-` placeholder check, so a prod boot refuses it."""
        proj = _create(tmp_path)
        text = (proj / ".env.local").read_text()
        assert "SECRET_KEY=django-insecure-dev-app-" in text
        assert "JWT_SECRET_KEY=django-insecure-dev-app-jwt-" in text
        assert "POSTGRES_PASSWORD=stapel" in text  # guard_db_password default set
        assert "STAPEL_LOCAL_ENV=1" in text        # deploy-gate marker flag
        assert "change_me" not in text

    def test_env_local_is_reproducible_across_generations(self, tmp_path):
        """A committed file must not churn: two generations of the same
        project produce byte-identical .env.local."""
        a = _create(tmp_path / "a")
        b = _create(tmp_path / "b")
        assert (a / ".env.local").read_text() == (b / ".env.local").read_text()

    def test_env_local_has_django_superuser_defaults_for_entrypoint_canon(self, tmp_path):
        proj = _create(tmp_path)
        text = (proj / ".env.local").read_text()
        assert "DJANGO_SUPERUSER_USERNAME=admin" in text
        assert "DJANGO_SUPERUSER_EMAIL=" in text
        # obviously-default (owner directive) — the deploy gate refuses it
        assert "DJANGO_SUPERUSER_PASSWORD=admin" in text

    def test_env_dev_has_vite_and_backend_targets(self, tmp_path):
        proj = _create(tmp_path)
        text = (proj / ".env.local").read_text()
        assert "BACKEND_UPSTREAM=svc-app:8000" in text
        assert "FRONTEND_LOCAL_UPSTREAM=frontend:5173" in text
        assert "VITE_BACKEND_TARGET=http://svc-app:8000" in text

    def test_env_dev_uses_dev_run_cmd_not_gunicorn(self, tmp_path):
        proj = _create(tmp_path)
        text = (proj / ".env.local").read_text()
        assert "RUN_CMD=python manage.py runserver 0.0.0.0:8000" in text

    def test_env_dev_defaults_to_inline_comm_bus_not_kafka(self, tmp_path):
        proj = _create(tmp_path)
        text = (proj / ".env.local").read_text()
        assert "KAFKA_BOOTSTRAP_SERVERS" not in text
        assert not any(
            line.startswith("STAPEL_BUS_BACKEND=") for line in text.splitlines()
        )  # no assignment at all = in-process + outbox (monolith default)

    def test_env_local_is_committed_stand_envs_are_ignored(self, tmp_path):
        """Owner decision: .env.local IS committed (a gitignored env never
        reaches the next clone); the STAND env names (.env.dev/.env.stage/
        .env.prod) are ignored — generated per stand, never committed."""
        proj = _create(tmp_path)
        gitignore = (proj / ".gitignore").read_text()
        ignored = [
            ln.strip() for ln in gitignore.splitlines()
            if ln.strip() and not ln.strip().startswith("#")
        ]
        assert ".env.local" not in ignored
        for stand_env in (".env.dev", ".env.stage", ".env.prod"):
            assert stand_env in ignored, stand_env

    def test_dev_compose_boots_dev_settings_module_with_hot_reload_mount(self, tmp_path):
        proj = _create(tmp_path)
        dev_compose = (proj / "docker-compose.local.yml").read_text()
        assert 'DJANGO_SETTINGS_MODULE: config.settings.dev' in dev_compose
        assert 'env_file: ".env.local"' in dev_compose
        assert "./svc-app:/app" in dev_compose

    def test_dev_compose_with_env_dev_is_valid_docker_compose_config(self, tmp_path):
        import shutil
        proj = _create(tmp_path)
        if shutil.which("docker") is None:
            yaml.safe_load((proj / "docker-compose.local.yml").read_text())
            return
        result = subprocess.run(
            ["docker", "compose", "-f", "docker-compose.local.yml",
             "--env-file", ".env.local", "config"],
            cwd=proj, capture_output=True, text=True,
        )
        assert result.returncode == 0, result.stdout + result.stderr
        data = yaml.safe_load(result.stdout)
        svc_app = data["services"]["svc-app"]
        assert svc_app["environment"]["DJANGO_SETTINGS_MODULE"] == "config.settings.dev"
        assert svc_app["command"][-1].endswith("manage.py runserver 0.0.0.0:8000")


class TestDevMockOtp:
    """Item 2: on a local stand, mock providers by default — email = console
    /mock (already the case via stapel-notifications' own "mock" provider
    default), phone/SMS OTP = stapel-auth's mock flow (code logged, never
    sent). Verified against the ACTUAL keys stapel-auth's otp/services.py
    reads (USE_MOCK_SMS_OTP / USE_MOCK_EMAIL_OTP, conf.py) — these are
    booleans in AppSettings' no_env list, so they can ONLY be set via the
    STAPEL_AUTH settings dict, never a plain env var."""

    def test_dev_settings_mocks_otp_when_auth_selected(self, tmp_path):
        proj = _create(tmp_path, modules=["core", "auth"])
        dev_settings = (proj / "svc-app" / "config" / "settings" / "dev.py").read_text()
        assert '"USE_MOCK_SMS_OTP": True' in dev_settings
        assert '"USE_MOCK_EMAIL_OTP": True' in dev_settings
        # merges over rather than clobbers any module_config STAPEL_AUTH block
        assert 'globals().get("STAPEL_AUTH", {})' in dev_settings

    def test_dev_settings_is_valid_python(self, tmp_path):
        proj = _create(tmp_path, modules=["core", "auth"])
        dev_settings_path = proj / "svc-app" / "config" / "settings" / "dev.py"
        compile(dev_settings_path.read_text(), "dev.py", "exec")

    def test_prod_settings_never_gets_mock_otp(self, tmp_path):
        proj = _create(tmp_path, modules=["core", "auth"])
        prod_settings = (proj / "svc-app" / "config" / "settings" / "prod.py").read_text()
        assert "USE_MOCK_SMS_OTP" not in prod_settings

    def test_no_auth_module_means_no_mock_otp_block(self, tmp_path):
        proj = _create(tmp_path, modules=["core"])
        dev_settings = (proj / "svc-app" / "config" / "settings" / "dev.py").read_text()
        assert "USE_MOCK_SMS_OTP" not in dev_settings

    def test_env_dev_documents_notifications_already_mock_by_default(self, tmp_path):
        """stapel-notifications' own conf.py DEFAULTS already set
        EMAIL_PROVIDER/SMS_PROVIDER to "mock" — no override needed here.
        Locks that fact in against the sibling checkout so a future
        notifications release changing the default doesn't silently break
        the "mock by default" gate this item promises; skips cleanly when
        the sibling workspace isn't checked out (e.g. module-only CI)."""
        from pathlib import Path

        notifications_conf = (
            Path(__file__).resolve().parents[2] / "stapel-notifications" / "conf.py"
        )
        if not notifications_conf.exists():
            pytest.skip("stapel-notifications sibling not present")
        text = notifications_conf.read_text()
        assert '"EMAIL_PROVIDER": "mock"' in text
        assert '"SMS_PROVIDER": "mock"' in text


class TestEnvPresets:
    """Item 3: standalone (default) vs studio channel-origin preset. Studio
    values are documented STUBS only — no real sender/OAuth infra."""

    def test_standalone_is_default_and_has_no_studio_stubs(self, tmp_path):
        proj = _create(tmp_path, env_preset="standalone")
        text = (proj / ".env.local").read_text()
        assert "NOTIFICATIONS_EMAIL_PROVIDER_STUDIO_TODO" not in text
        assert "STAPEL_STUDIO_OAUTH_CLIENT_ID" not in text
        assert "stapel_sender.EmailProvider" not in text

    def test_studio_preset_has_documented_stubs_with_todo(self, tmp_path):
        proj = _create(tmp_path, env_preset="studio")
        text = (proj / ".env.local").read_text()
        assert "TODO(§57 studio preset)" in text
        assert "NOTIFICATIONS_EMAIL_PROVIDER_STUDIO_TODO=stapel_sender.EmailProvider" in text
        assert "STAPEL_STUDIO_OAUTH_CLIENT_ID=" in text
        assert "STAPEL_STUDIO_OAUTH_CLIENT_SECRET=" in text

    def test_studio_preset_still_has_the_working_baseline(self, tmp_path):
        """The studio preset is additive — everything standalone gives you
        (real secrets, superuser defaults, Vite targets) still applies."""
        proj = _create(tmp_path, env_preset="studio")
        text = (proj / ".env.local").read_text()
        assert "DJANGO_SUPERUSER_USERNAME=admin" in text
        assert "BACKEND_UPSTREAM=svc-app:8000" in text
        assert "change_me" not in text

    def test_invalid_preset_is_a_hard_error(self, tmp_path):
        with pytest.raises(SystemExit):
            _create(tmp_path, env_preset="bogus")

    def test_cli_accepts_env_preset_flag(self):
        from stapel_tools.create_project import main as cp_main

        result = subprocess.run(
            [sys.executable, "-m", "stapel_tools.create_project", "--help"],
            capture_output=True, text=True,
        )
        assert "--env-preset" in result.stdout
        assert cp_main  # imported to prove the module itself still loads


class TestAssembleScaffoldEnvPreset:
    def test_assemble_scaffold_accepts_env_preset(self, tmp_path):
        from stapel_tools.assemble_scaffold import assemble_scaffold

        result = assemble_scaffold(
            "app", libs=[], output_dir=tmp_path, project_type="monolith",
            verify=False, env_preset="studio",
        )
        text = (result.project_dir / ".env.local").read_text()
        assert "TODO(§57 studio preset)" in text
