"""§57 owner directive item 7 — dev-env generated by the framework so a
project works right after `docker compose up`, zero manual config: `.env.dev`
(real secrets + working defaults), dev-only mock OTP providers, and the
standalone/studio channel-origin presets."""
import subprocess
import sys

import pytest
import yaml

from stapel_tools.create_project import create_project


def _create(tmp_path, name="app", modules=None, env_preset="standalone"):
    create_project(
        name=name, project_type="monolith", title=name.capitalize(),
        url="https://x.dev", company_name="X", company_email="x@x.dev",
        modules=modules or ["core"], output_dir=tmp_path,
        use_submodules=False, init_git=False, env_preset=env_preset,
    )
    return tmp_path / name


class TestEnvDevGenerated:
    def test_env_dev_written_with_real_secrets_not_placeholders(self, tmp_path):
        proj = _create(tmp_path)
        text = (proj / ".env.dev").read_text()
        assert "change_me" not in text
        assert "SECRET_KEY=" in text
        secret = next(
            ln.split("=", 1)[1] for ln in text.splitlines()
            if ln.startswith("SECRET_KEY=")
        )
        assert len(secret) >= 32

    def test_env_dev_two_projects_get_different_secrets(self, tmp_path):
        a = _create(tmp_path / "a")
        b = _create(tmp_path / "b")
        secret_a = (a / ".env.dev").read_text()
        secret_b = (b / ".env.dev").read_text()
        assert secret_a != secret_b

    def test_env_dev_has_django_superuser_defaults_for_entrypoint_canon(self, tmp_path):
        proj = _create(tmp_path)
        text = (proj / ".env.dev").read_text()
        assert "DJANGO_SUPERUSER_USERNAME=admin" in text
        assert "DJANGO_SUPERUSER_EMAIL=" in text
        password = next(
            ln.split("=", 1)[1] for ln in text.splitlines()
            if ln.startswith("DJANGO_SUPERUSER_PASSWORD=")
        )
        assert len(password) >= 16

    def test_env_dev_has_vite_and_backend_targets(self, tmp_path):
        proj = _create(tmp_path)
        text = (proj / ".env.dev").read_text()
        assert "BACKEND_UPSTREAM=svc-app:8000" in text
        assert "FRONTEND_DEV_UPSTREAM=frontend:5173" in text
        assert "VITE_BACKEND_TARGET=http://svc-app:8000" in text

    def test_env_dev_uses_dev_run_cmd_not_gunicorn(self, tmp_path):
        proj = _create(tmp_path)
        text = (proj / ".env.dev").read_text()
        assert "RUN_CMD=python manage.py runserver 0.0.0.0:8000" in text

    def test_env_dev_defaults_to_inline_comm_bus_not_kafka(self, tmp_path):
        proj = _create(tmp_path)
        text = (proj / ".env.dev").read_text()
        assert "KAFKA_BOOTSTRAP_SERVERS" not in text
        assert not any(
            line.startswith("STAPEL_BUS_BACKEND=") for line in text.splitlines()
        )  # no assignment at all = in-process + outbox (monolith default)

    def test_env_dev_is_gitignored(self, tmp_path):
        proj = _create(tmp_path)
        gitignore = (proj / ".gitignore").read_text()
        assert ".env.dev" in gitignore

    def test_dev_compose_boots_dev_settings_module_with_hot_reload_mount(self, tmp_path):
        proj = _create(tmp_path)
        dev_compose = (proj / "docker-compose.dev.yml").read_text()
        assert 'DJANGO_SETTINGS_MODULE: config.settings.dev' in dev_compose
        assert 'env_file: ".env.dev"' in dev_compose
        assert "./svc-app:/app" in dev_compose

    def test_dev_compose_with_env_dev_is_valid_docker_compose_config(self, tmp_path):
        import shutil
        proj = _create(tmp_path)
        if shutil.which("docker") is None:
            yaml.safe_load((proj / "docker-compose.dev.yml").read_text())
            return
        result = subprocess.run(
            ["docker", "compose", "-f", "docker-compose.dev.yml",
             "--env-file", ".env.dev", "config"],
            cwd=proj, capture_output=True, text=True,
        )
        assert result.returncode == 0, result.stdout + result.stderr
        data = yaml.safe_load(result.stdout)
        svc_app = data["services"]["svc-app"]
        assert svc_app["environment"]["DJANGO_SETTINGS_MODULE"] == "config.settings.dev"
        assert svc_app["command"][-1].endswith("manage.py runserver 0.0.0.0:8000")


class TestDevMockOtp:
    """Item 2: on a local stand, mock providers by default — email = console
    /mock (already the case via stapel-notifications' own "mock" provider
    default), phone/SMS OTP = stapel-auth's mock flow (code logged, never
    sent). Verified against the ACTUAL keys stapel-auth's otp/services.py
    reads (USE_MOCK_SMS_OTP / USE_MOCK_EMAIL_OTP, conf.py) — these are
    booleans in AppSettings' no_env list, so they can ONLY be set via the
    STAPEL_AUTH settings dict, never a plain env var."""

    def test_dev_settings_mocks_otp_when_auth_selected(self, tmp_path):
        proj = _create(tmp_path, modules=["core", "auth"])
        dev_settings = (proj / "svc-app" / "config" / "settings" / "dev.py").read_text()
        assert '"USE_MOCK_SMS_OTP": True' in dev_settings
        assert '"USE_MOCK_EMAIL_OTP": True' in dev_settings
        # merges over rather than clobbers any module_config STAPEL_AUTH block
        assert 'globals().get("STAPEL_AUTH", {})' in dev_settings

    def test_dev_settings_is_valid_python(self, tmp_path):
        proj = _create(tmp_path, modules=["core", "auth"])
        dev_settings_path = proj / "svc-app" / "config" / "settings" / "dev.py"
        compile(dev_settings_path.read_text(), "dev.py", "exec")

    def test_prod_settings_never_gets_mock_otp(self, tmp_path):
        proj = _create(tmp_path, modules=["core", "auth"])
        prod_settings = (proj / "svc-app" / "config" / "settings" / "prod.py").read_text()
        assert "USE_MOCK_SMS_OTP" not in prod_settings

    def test_no_auth_module_means_no_mock_otp_block(self, tmp_path):
        proj = _create(tmp_path, modules=["core"])
        dev_settings = (proj / "svc-app" / "config" / "settings" / "dev.py").read_text()
        assert "USE_MOCK_SMS_OTP" not in dev_settings

    def test_env_dev_documents_notifications_already_mock_by_default(self, tmp_path):
        """stapel-notifications' own conf.py DEFAULTS already set
        EMAIL_PROVIDER/SMS_PROVIDER to "mock" — no override needed here.
        Locks that fact in against the sibling checkout so a future
        notifications release changing the default doesn't silently break
        the "mock by default" gate this item promises; skips cleanly when
        the sibling workspace isn't checked out (e.g. module-only CI)."""
        from pathlib import Path

        notifications_conf = (
            Path(__file__).resolve().parents[2] / "stapel-notifications" / "conf.py"
        )
        if not notifications_conf.exists():
            pytest.skip("stapel-notifications sibling not present")
        text = notifications_conf.read_text()
        assert '"EMAIL_PROVIDER": "mock"' in text
        assert '"SMS_PROVIDER": "mock"' in text


class TestEnvPresets:
    """Item 3: standalone (default) vs studio channel-origin preset. Studio
    values are documented STUBS only — no real sender/OAuth infra."""

    def test_standalone_is_default_and_has_no_studio_stubs(self, tmp_path):
        proj = _create(tmp_path, env_preset="standalone")
        text = (proj / ".env.dev").read_text()
        assert "NOTIFICATIONS_EMAIL_PROVIDER_STUDIO_TODO" not in text
        assert "STAPEL_STUDIO_OAUTH_CLIENT_ID" not in text
        assert "stapel_sender.EmailProvider" not in text

    def test_studio_preset_has_documented_stubs_with_todo(self, tmp_path):
        proj = _create(tmp_path, env_preset="studio")
        text = (proj / ".env.dev").read_text()
        assert "TODO(§57 studio preset)" in text
        assert "NOTIFICATIONS_EMAIL_PROVIDER_STUDIO_TODO=stapel_sender.EmailProvider" in text
        assert "STAPEL_STUDIO_OAUTH_CLIENT_ID=" in text
        assert "STAPEL_STUDIO_OAUTH_CLIENT_SECRET=" in text

    def test_studio_preset_still_has_the_working_baseline(self, tmp_path):
        """The studio preset is additive — everything standalone gives you
        (real secrets, superuser defaults, Vite targets) still applies."""
        proj = _create(tmp_path, env_preset="studio")
        text = (proj / ".env.dev").read_text()
        assert "DJANGO_SUPERUSER_USERNAME=admin" in text
        assert "BACKEND_UPSTREAM=svc-app:8000" in text
        assert "change_me" not in text

    def test_invalid_preset_is_a_hard_error(self, tmp_path):
        with pytest.raises(SystemExit):
            _create(tmp_path, env_preset="bogus")

    def test_cli_accepts_env_preset_flag(self):
        from stapel_tools.create_project import main as cp_main

        result = subprocess.run(
            [sys.executable, "-m", "stapel_tools.create_project", "--help"],
            capture_output=True, text=True,
        )
        assert "--env-preset" in result.stdout
        assert cp_main  # imported to prove the module itself still loads


class TestAssembleScaffoldEnvPreset:
    def test_assemble_scaffold_accepts_env_preset(self, tmp_path):
        from stapel_tools.assemble_scaffold import assemble_scaffold

        result = assemble_scaffold(
            "app", libs=[], output_dir=tmp_path, project_type="monolith",
            verify=False, env_preset="studio",
        )
        text = (result.project_dir / ".env.dev").read_text()
        assert "TODO(§57 studio preset)" in text
