"""``deploy/`` scaffold — owner decision, §57 revision: the generator emits
prod/stage deploy scripts WITH a hard gate against the default/committed dev
env. The committed ``.env.local`` (see _local_env_templates.py) is safe exactly
because these scripts (and stapel-core's prodguard at boot) refuse it.

Two files, both POSIX sh (no bashisms — runs on any stand):

- ``deploy/check-env.sh <env-file>`` — the gate itself, standalone so CI can
  call it too. Refuses an env carrying ANY dev marker:
    * ``STAPEL_LOCAL_ENV=1``           (the committed dev env's explicit flag)
    * ``SECRET_KEY``/``JWT_SECRET_KEY`` with a placeholder/dev prefix
      (django-insecure-, dev-insecure-, change_me/changeme) or missing
      SECRET_KEY entirely
    * ``DEBUG=true``                  (any casing)
    * ``DJANGO_ENV`` set to anything but ``prod``
    * ``POSTGRES_PASSWORD`` in the known default set (stapel/change_me/…)
    * ``DJANGO_SUPERUSER_PASSWORD=admin`` (the dev default)
    * ``EMAIL_PROVIDER=mock`` / ``SMS_PROVIDER=mock`` set explicitly
  Mirrors (a superset of) what stapel-core's prodguard enforces at boot —
  the script version fails BEFORE containers restart, the prodguard version
  fails even if someone bypasses the script. NOTE for core (candidate): the
  in-boot guard today covers secrets/db-password only; a prodguard-class
  system check for "mock provider while not DEBUG" does not exist yet.

- ``deploy/deploy.sh [env-file]`` — gate + build + up over the PROD compose
  (docker-compose.yml; never docker-compose.local.yml). Default env-file:
  ``.env`` at the project root. Run it on the stand, from anywhere.

- ``deploy/preflight.sh [env-file]`` (env-address-class-v2.md §3.5) —
  probes every env-boundary upstream (``PREFLIGHT_TARGETS``, same
  ``name=host:port`` shape as the nginx gate's ``UPSTREAM_GATE_TARGETS``)
  from a ONE-SHOT container placed in the project's own compose network —
  the actual seam nginx will use, not a guess from the host's own routing.
  Reuses ``service-configs/nginx/40-upstream-gate.sh``'s ``--probe-only``
  mode (single source of truth for the resolve/probe/triage diagnosis, so
  preflight and the running gate can never disagree). Called from
  ``deploy.sh`` BEFORE ``up`` — the ONE place in this whole class where
  fail-closed on a reachability problem is the correct answer: stopping a
  deploy before it restarts anything is not the same as taking the running
  site down (env-address-class-v2.md §3.5's own distinction). No
  ``PREFLIGHT_TARGETS`` set -> nothing to probe (a project with no
  host-network dependency), exits 0.
"""

CHECK_ENV_SH = """\
#!/bin/sh
# deploy/check-env.sh — hard gate against deploying a dev/default env
# (generated by stapel-create-project; owner decision, §57 revision).
#
# Usage: deploy/check-env.sh <env-file>
# Exit 0 = env acceptable for a stand; exit 1 = dev/default markers found.
set -eu

ENV_FILE="${1:?usage: check-env.sh <env-file>}"

if [ ! -f "$ENV_FILE" ]; then
    echo "check-env: $ENV_FILE does not exist" >&2
    exit 1
fi

fail=0
say() { echo "check-env: $ENV_FILE: $1" >&2; fail=1; }

# Read a key's value (last assignment wins, comments ignored).
get() {
    grep -E "^[[:space:]]*$1=" "$ENV_FILE" | tail -n 1 | cut -d= -f2- \
        | tr -d '"' | tr -d "'" || true
}

lower() { printf '%s' "$1" | tr '[:upper:]' '[:lower:]'; }

# 1. The committed dev env carries an explicit machine-readable flag.
if [ -n "$(get STAPEL_LOCAL_ENV)" ]; then
    say "STAPEL_LOCAL_ENV is set — this is the COMMITTED LOCAL DEV env (.env.local). Deploying it is forbidden; generate a real prod env (fresh random secrets, see .env.example)."
fi

# 2. Placeholder / dev-marked secrets (same prefix family stapel-core's
#    prodguard refuses at boot; the script fails before containers restart).
for key in SECRET_KEY JWT_SECRET_KEY; do
    value="$(lower "$(get "$key")")"
    case "$value" in
        django-insecure-*|dev-insecure-*|change_me*|changeme*)
            say "$key is a dev/placeholder value ('$(get "$key" | cut -c1-24)…'). Generate a real random secret." ;;
    esac
done
if [ -z "$(get SECRET_KEY)" ]; then
    say "SECRET_KEY is missing/empty. A stand env must set a real random secret."
fi

# 3. Debug / env-tier markers.
case "$(lower "$(get DEBUG)")" in
    true|1|yes) say "DEBUG=true — a stand never runs with DEBUG on." ;;
esac
env_tier="$(get DJANGO_ENV)"
if [ -n "$env_tier" ] && [ "$env_tier" != "prod" ]; then
    say "DJANGO_ENV=$env_tier — a stand env must set DJANGO_ENV=prod (or omit it for the compose prod settings tier)."
fi

# 4. Default credentials.
case "$(lower "$(get POSTGRES_PASSWORD)")" in
    stapel|change_me|changeme|"")
        say "POSTGRES_PASSWORD is the default/placeholder. Set a real random password." ;;
esac
if [ "$(lower "$(get DJANGO_SUPERUSER_PASSWORD)")" = "admin" ]; then
    say "DJANGO_SUPERUSER_PASSWORD=admin is the dev default. Set a real password or unset to skip superuser auto-creation."
fi

# 5. Mock providers pinned explicitly (dev-only convenience).
for key in EMAIL_PROVIDER SMS_PROVIDER; do
    if [ "$(lower "$(get "$key")")" = "mock" ]; then
        say "$key=mock — a stand must use a real provider."
    fi
done

if [ "$fail" -ne 0 ]; then
    echo "" >&2
    echo "check-env: REFUSING to deploy a default/dev env. Generate a real prod env — the default is forbidden (see .env.example; stapel-core prodguard would refuse these values at boot anyway)." >&2
    exit 1
fi
echo "check-env: $ENV_FILE looks deployable (no dev/default markers)."
"""

PREFLIGHT_SH = """\
#!/bin/sh
# deploy/preflight.sh — probe every env-boundary upstream from a ONE-SHOT
# container in the project's own compose network, BEFORE deploy.sh restarts
# anything (generated by stapel-create-project;
# docs/pending/env-address-class-v2.md §3.5).
#
# Why a separate probe from the host, not just trusting the running gate:
# the running nginx gate (service-configs/nginx/40-upstream-gate.sh) NEVER
# blocks a start on an unreachable upstream (v2 policy — environment errors
# degrade loudly, they do not fail closed, so a broken seam does not take
# the rest of the site with it). That is exactly right for a container that
# is ALREADY serving traffic — and exactly wrong for a deploy that has not
# happened yet: here, refusing to proceed costs nothing (the OLD containers
# are still up and serving), so failing closed on a real reachability
# problem is strictly better than shipping a known-broken seam. This is the
# ONE place in the whole class where fail-closed is the right answer.
#
# Usage: deploy/preflight.sh [env-file]      (default: .env)
# Reads PREFLIGHT_TARGETS ("name=host:port ..." — same shape as the nginx
# gate's UPSTREAM_GATE_TARGETS) from the given env-file, or from the
# PREFLIGHT_TARGETS process env (process env wins). Not set/empty -> nothing
# to probe (a project with no host-network dependency configured) -> exit 0.
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

ENV_FILE="${1:-.env}"

get() {
    [ -f "$ENV_FILE" ] || return 0
    grep -E "^[[:space:]]*$1=" "$ENV_FILE" | tail -n 1 | cut -d= -f2- \\
        | tr -d '"' | tr -d "'" || true
}

TARGETS="${PREFLIGHT_TARGETS:-$(get PREFLIGHT_TARGETS)}"

if [ -z "$TARGETS" ]; then
    echo "preflight: PREFLIGHT_TARGETS not set (checked env $ENV_FILE and the process environment) — nothing to probe, skipping."
    exit 0
fi

GATE_SCRIPT="service-configs/nginx/40-upstream-gate.sh"
if [ ! -f "$GATE_SCRIPT" ]; then
    echo "preflight: PREFLIGHT_TARGETS is set but $GATE_SCRIPT does not exist — nothing to reuse its probe/diagnosis logic from. Add the gate script (docs/pending/env-address-class-v2.md §3.4) before wiring PREFLIGHT_TARGETS." >&2
    exit 1
fi

# The default compose project name IS the directory name (docker compose's
# own rule) — override with PREFLIGHT_NETWORK or COMPOSE_PROJECT_NAME if a
# project's compose invocation pins a different one (-p / .env's
# COMPOSE_PROJECT_NAME).
NETWORK="${PREFLIGHT_NETWORK:-${COMPOSE_PROJECT_NAME:-$(basename "$PROJECT_ROOT")}_default}"

target_count=$(echo "$TARGETS" | wc -w | tr -d ' ')
echo "preflight: probing $target_count target(s) in network \\"$NETWORK\\" (the actual seam nginx will use) ..."

fail=0
for entry in $TARGETS; do
    name="${entry%%=*}"
    if docker run --rm --network "$NETWORK" \\
        -v "$PROJECT_ROOT/$GATE_SCRIPT:/gate.sh:ro" \\
        alpine:3.20 sh /gate.sh --probe-only "$entry"; then
        echo "preflight: $name OK"
    else
        echo "preflight: $name UNREACHABLE from network $NETWORK — see diagnosis above." >&2
        fail=1
    fi
done

if [ "$fail" -ne 0 ]; then
    echo "" >&2
    echo "preflight: REFUSING to deploy — at least one env-boundary upstream is unreachable from the project's own network. The OLD containers are still up; fix the seam, then re-run deploy.sh." >&2
    exit 1
fi

echo "preflight: all targets reachable."
"""

DEPLOY_SH = """\
#!/bin/sh
# deploy/deploy.sh — prod/stage deploy over the PROD compose file
# (generated by stapel-create-project; owner decision, §57 revision).
#
# Usage (from anywhere; env-file path is relative to the project root):
#   deploy/deploy.sh              # uses .env
#   deploy/deploy.sh .env.stage   # a stage env you generated
#
# Env-file naming canon: `.env.local` is the COMMITTED local-machine env
# (never deployable — the gate refuses it). The names `.env.dev`,
# `.env.stage`, `.env.prod` are RESERVED for STANDS: generated per stand
# with real random secrets (shape: .env.example), gitignored, never
# committed. "dev" in a file name means the dev STAND, not your machine.
#
# HARD GATE: refuses to run against an env carrying dev/default markers
# (the committed .env.local, placeholder secrets, DEBUG=true, mock providers)
# — see deploy/check-env.sh. Generate a real env per stand; never reuse the
# committed local-machine one.
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

ENV_FILE="${1:-.env}"

sh "$SCRIPT_DIR/check-env.sh" "$ENV_FILE"
sh "$SCRIPT_DIR/preflight.sh" "$ENV_FILE"

echo "deploy: building images (docker-compose.yml, env: $ENV_FILE)..."
docker compose --env-file "$ENV_FILE" -f docker-compose.yml build

echo "deploy: starting services..."
docker compose --env-file "$ENV_FILE" -f docker-compose.yml up -d --remove-orphans

echo "deploy: done. Status:"
docker compose --env-file "$ENV_FILE" -f docker-compose.yml ps
"""
