"""stapel-gen-client — project-owned typed TS client override (tier 2 of the
owner directive answer to "раз мы оверрайдим профайл, его фронтенд-пара
должна уметь это грамотно обрабатывать": `docs/pending/profile-fields.md`
"Дополнение владельца" §17.07).

Tier 1 (data-driven skin off a runtime field-manifest endpoint) is a
`stapel-profiles`/frontend-pair concern, out of this repo's scope. Tier 2 is
the UNIVERSAL mechanism, for ANY overridden library, not profile-specific:
regenerate a typed TS client from the PROJECT'S OWN committed
``schema.json`` (its own OpenAPI slice — see `_docgen_scan` for the three
supported layouts), not the library's upstream one, into a project-owned
override directory a pair's generated api-layer can be swapped for (the
existing client-injection seam — frontend-standard §7.2 — the pair already
depends on an injected `client`/api object, not a hardcoded import).

Generation core: **openapi-typescript** — the exact engine stapel-react's
own `scripts/gen-api.mjs` uses (v7, types-only, zero runtime). This module
does not reimplement it; it shells out to the same package via `npx`, the
same way any Node project consumes it. That keeps stapel-tools dependency-
free (it ships zero runtime deps by design — see `config_manifest.py`'s
docstring) while still reusing the one generation core, not forking it.

Output: ``frontend/src/api/generated-override/<module>/schema.ts`` — one
file per discovered module slice, mirroring the pair's own
``src/api/generated/schema.ts`` shape so a project can point its hand-authored
api layer (the ``profilesApi.ts``-style file) at this path instead.

Activation gate — "активен ТОЛЬКО если в проекте есть оверрайды": this
command (and the pre-commit hook that always calls it with `--check`) is a
deliberate NO-OP, exit 0, unless :func:`override_active` finds a real signal
that the project overrides a stapel default. See that function's docstring
for the two signals and why PRESENTERS.MD-diffing was rejected as dishonest
(no machine-readable stock baseline exists to diff against).

Exit codes: 0 clean/no-op, 1 check-mode drift, 2 usage/generation error.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

from ._docgen_scan import ModuleDocs, discover_modules

GENERATED_OVERRIDE_DIR = "frontend/src/api/generated-override"
OVERRIDE_MANIFEST = "stapel.override.json"

_HEADER = """\
// AUTO-GENERATED by `stapel-gen-client` — do not edit by hand.
// Source: THIS PROJECT'S OWN schema.json (not a library's upstream one) —
// the tier-2 override mechanism (docs/pending/profile-fields.md "Дополнение
// владельца §17.07"). Point your api layer at this file's types instead of
// (or on top of) the pair's own `generated/schema.ts` when you've overridden
// that module's backend contract.
// Regenerate: stapel-gen-client .   ·   Drift gate: stapel-gen-client . --check
// Generation core: openapi-typescript (the same engine stapel-react's own
// scripts/gen-api.mjs uses) — invoked via npx, not reimplemented.
"""

_SWAP_ASSIGN_RE = re.compile(r"STAPEL_SWAP\s*=\s*\{(?P<body>[^}]*)\}", re.DOTALL)
_NONEMPTY_ENTRY_RE = re.compile(r"""['"][^'"]+['"]\s*:\s*['"][^'"]+['"]""")


class GenClientError(Exception):
    """openapi-typescript failed, or `node`/`npx` is unavailable."""


def _has_nonempty_swap(text: str) -> bool:
    for match in _SWAP_ASSIGN_RE.finditer(text):
        if _NONEMPTY_ENTRY_RE.search(match.group("body")):
            return True
    return False


def override_active(project_dir: Path) -> bool:
    """Tier-2 activation gate — a real, minimally-honest signal that this
    project overrides a stapel default, not a guess:

    1. **Explicit manifest flag** — ``stapel.override.json`` at the project
       root with a truthy ``"clientOverride"`` key. The cheapest, most
       honest signal for the cases the STAPEL_SWAP scan below cannot see
       (e.g. the attributes-bridge case: extra profile fields added without
       swapping any class).
    2. **A non-empty ``STAPEL_SWAP = {...}``** in any committed ``.py``
       file — the mechanism PRESENTERS.MD itself documents ("a host
       replaces any class below through the STAPEL_SWAP setting"). Already
       exists, already means exactly "this project overrides a default" —
       reused, not invented.

    Deliberately does NOT diff PRESENTERS.MD against "the defaults": that
    file renders each swap point's *declared* default (a library constant,
    unaffected by what a host activates via settings), so no divergence
    would ever show up there for a real override — diffing it would be a
    guess dressed as a signal, not a fact.
    """
    manifest = project_dir / OVERRIDE_MANIFEST
    if manifest.is_file():
        try:
            data = json.loads(manifest.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            data = {}
        if isinstance(data, dict) and data.get("clientOverride"):
            return True

    from ._docgen_scan import SKIP_DIRS

    for path in sorted(project_dir.rglob("*.py")):
        if any(part in SKIP_DIRS or part.startswith(".") for part in path.parts):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if "STAPEL_SWAP" in text and _has_nonempty_swap(text):
            return True
    return False


def _out_path(project_dir: Path, mod: ModuleDocs) -> Path:
    return project_dir / GENERATED_OVERRIDE_DIR / mod.name / "schema.ts"


def _render(schema_path: Path) -> str:
    """Run openapi-typescript over *schema_path*, return the header-prefixed
    TS source. Raises :class:`GenClientError` on any failure (missing
    node/npx, invalid schema, non-zero exit)."""
    with tempfile.TemporaryDirectory() as td:
        tmp_out = Path(td) / "schema.ts"
        try:
            proc = subprocess.run(
                ["npx", "--yes", "openapi-typescript@^7", str(schema_path), "-o", str(tmp_out)],
                capture_output=True, text=True,
            )
        except FileNotFoundError as exc:
            raise GenClientError(
                f"`npx` not found on PATH — install Node.js to run stapel-gen-client ({exc})"
            ) from exc
        if proc.returncode != 0 or not tmp_out.is_file():
            detail = (proc.stderr or proc.stdout or "").strip()
            raise GenClientError(f"openapi-typescript failed for {schema_path}: {detail}")
        return _HEADER + tmp_out.read_text(encoding="utf-8")


def run(project_dir: Path, *, check: bool = False, force: bool = False) -> int:
    if not force and not override_active(project_dir):
        print(
            "stapel-gen-client: no override detected (no stapel.override.json "
            "clientOverride flag, no non-empty STAPEL_SWAP anywhere in the "
            "project) — no-op."
        )
        return 0

    modules = discover_modules(project_dir)
    if not modules:
        print(
            "stapel-gen-client: override detected but no committed schema.json "
            "found (docs/schema.json, codegen/generated/schema.json, or a "
            "per-module <mod>/api/v1/schema.json) — nothing to generate from.",
            file=sys.stderr,
        )
        return 0

    drifted: list[str] = []
    for mod in modules:
        out_path = _out_path(project_dir, mod)
        try:
            new_text = _render(mod.schema_json)
        except GenClientError as exc:
            print(f"stapel-gen-client: {exc}", file=sys.stderr)
            return 2

        if check:
            old_text = out_path.read_text(encoding="utf-8") if out_path.is_file() else None
            if old_text != new_text:
                drifted.append(str(out_path))
            continue

        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(new_text, encoding="utf-8")
        print(f"stapel-gen-client: {mod.name} -> {out_path}")

    if check:
        if drifted:
            print(
                "stapel-gen-client --check: drift — regenerate with "
                "`stapel-gen-client .` and commit:\n  " + "\n  ".join(drifted),
                file=sys.stderr,
            )
            return 1
        print(f"stapel-gen-client --check: {len(modules)} module(s) up to date.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="stapel-gen-client",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "project_dir", nargs="?", default=".",
        help="Project directory (default: .).",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Do not write — exit 1 if regenerating would change any file "
             "(drift gate for pre-commit).",
    )
    parser.add_argument(
        "--force", action="store_true",
        help="Generate even without an override signal (manual escape hatch; "
             "the pre-commit hook never passes this).",
    )
    args = parser.parse_args(argv)
    return run(Path(args.project_dir), check=args.check, force=args.force)


if __name__ == "__main__":
    raise SystemExit(main())
